export interface Cita {
  id: string;
  numeroSolicitud: string;
  cliente: {
    id: string;
    nombre: string;
    email: string;
    telefono: string;
  };
  tipoTramite: string;
  fecha: string; // YYYY-MM-DD
  hora: string; // HH:MM
  duracion: number; // en minutos
  sala: string;
  estado: "PROGRAMADA" | "EN_CURSO" | "COMPLETADA" | "CANCELADA";
  notas?: string;
  abogadoId: string;
}

// Función para generar hora actual + minutos
const getHoraActualMasMinutos = (minutos: number): string => {
  const ahora = new Date();
  const nuevaHora = new Date(ahora.getTime() + minutos * 60 * 1000);
  const horas = nuevaHora.getHours().toString().padStart(2, "0");
  const mins = nuevaHora.getMinutes().toString().padStart(2, "0");
  return `${horas}:${mins}`;
};

// Array para almacenar todas las citas
export const citas: Cita[] = [
  {
    id: "CITA-001",
    numeroSolicitud: "NT3-2025-00123",
    cliente: {
      id: "cliente-1",
      nombre: "María González López",
      email: "maria.gonzalez@email.com",
      telefono: "664-123-4567",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-16", // Hoy
    hora: getHoraActualMasMinutos(15), // En 15 minutos (PRÓXIMA)
    duracion: 60,
    sala: "Sala de Audiencias A",
    estado: "PROGRAMADA",
    notas: "Revisión de documentos y firma del testamento",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-002",
    numeroSolicitud: "NT3-2025-00124",
    cliente: {
      id: "cliente-2",
      nombre: "Carlos Rodríguez Martínez",
      email: "carlos.rodriguez@email.com",
      telefono: "664-234-5678",
    },
    tipoTramite: "Escritura de Compraventa",
    fecha: "2025-09-16", // Hoy
    hora: getHoraActualMasMinutos(90), // En 1.5 horas
    duracion: 90,
    sala: "Sala de Audiencias B",
    estado: "PROGRAMADA",
    notas: "Firma de escritura de compraventa de inmueble",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-003",
    numeroSolicitud: "NT3-2025-00125",
    cliente: {
      id: "cliente-3",
      nombre: "Ana Patricia Herrera",
      email: "ana.herrera@email.com",
      telefono: "664-345-6789",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-09-17", // Mañana
    hora: "10:00",
    duracion: 45,
    sala: "Sala de Audiencias A",
    estado: "PROGRAMADA",
    notas: "Otorgamiento de poder notarial para gestión de bienes",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-004",
    numeroSolicitud: "NT3-2025-00126",
    cliente: {
      id: "cliente-4",
      nombre: "Roberto Silva Torres",
      email: "roberto.silva@email.com",
      telefono: "664-456-7890",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-17", // Mañana
    hora: "14:00",
    duracion: 60,
    sala: "Sala de Audiencias C",
    estado: "PROGRAMADA",
    notas: "Revisión y firma de testamento",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-005",
    numeroSolicitud: "NT3-2025-00127",
    cliente: {
      id: "cliente-5",
      nombre: "Laura Méndez García",
      email: "laura.mendez@email.com",
      telefono: "664-567-8901",
    },
    tipoTramite: "Escritura de Donación",
    fecha: "2025-09-18", // Pasado mañana
    hora: "15:30",
    duracion: 75,
    sala: "Sala de Audiencias B",
    estado: "PROGRAMADA",
    notas: "Firma de escritura de donación de vehículo",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-006",
    numeroSolicitud: "NT3-2025-00128",
    cliente: {
      id: "cliente-6",
      nombre: "Miguel Ángel Pérez",
      email: "miguel.perez@email.com",
      telefono: "664-678-9012",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-09-15", // Ayer (completada)
    hora: "16:00",
    duracion: 45,
    sala: "Sala de Audiencias A",
    estado: "COMPLETADA",
    notas: "Poder notarial para representación legal",
    abogadoId: "abogado-1",
  },
  // Citas adicionales para la próxima semana
  {
    id: "CITA-007",
    numeroSolicitud: "NT3-2025-00129",
    cliente: {
      id: "cliente-7",
      nombre: "Isabel Cristina Vega",
      email: "isabel.vega@email.com",
      telefono: "664-789-0123",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-20",
    hora: "09:00",
    duracion: 60,
    sala: "Sala de Audiencias A",
    estado: "PROGRAMADA",
    notas: "Revisión final y firma de testamento",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-008",
    numeroSolicitud: "NT3-2025-00130",
    cliente: {
      id: "cliente-8",
      nombre: "Fernando López Morales",
      email: "fernando.lopez@email.com",
      telefono: "664-890-1234",
    },
    tipoTramite: "Escritura de Compraventa",
    fecha: "2025-09-20",
    hora: "11:30",
    duracion: 90,
    sala: "Sala de Audiencias B",
    estado: "PROGRAMADA",
    notas: "Firma de escritura de compraventa de casa habitación",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-009",
    numeroSolicitud: "NT3-2025-00131",
    cliente: {
      id: "cliente-9",
      nombre: "Carmen Rosa Delgado",
      email: "carmen.delgado@email.com",
      telefono: "664-901-2345",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-09-21",
    hora: "10:30",
    duracion: 45,
    sala: "Sala de Audiencias C",
    estado: "PROGRAMADA",
    notas: "Poder notarial para administración de bienes",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-010",
    numeroSolicitud: "NT3-2025-00132",
    cliente: {
      id: "cliente-10",
      nombre: "José Antonio Ruiz",
      email: "jose.ruiz@email.com",
      telefono: "664-012-3456",
    },
    tipoTramite: "Escritura de Donación",
    fecha: "2025-09-21",
    hora: "15:00",
    duracion: 75,
    sala: "Sala de Audiencias A",
    estado: "PROGRAMADA",
    notas: "Donación de terreno a favor de hijo",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-011",
    numeroSolicitud: "NT3-2025-00133",
    cliente: {
      id: "cliente-11",
      nombre: "Patricia Elena Sánchez",
      email: "patricia.sanchez@email.com",
      telefono: "664-123-4567",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-22",
    hora: "08:30",
    duracion: 60,
    sala: "Sala de Audiencias B",
    estado: "PROGRAMADA",
    notas: "Modificación de testamento existente",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-012",
    numeroSolicitud: "NT3-2025-00134",
    cliente: {
      id: "cliente-12",
      nombre: "Ricardo Mendoza Castro",
      email: "ricardo.mendoza@email.com",
      telefono: "664-234-5678",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-09-22",
    hora: "13:00",
    duracion: 45,
    sala: "Sala de Audiencias C",
    estado: "PROGRAMADA",
    notas: "Poder notarial para representación en juicio",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-013",
    numeroSolicitud: "NT3-2025-00135",
    cliente: {
      id: "cliente-13",
      nombre: "Sandra Beatriz Flores",
      email: "sandra.flores@email.com",
      telefono: "664-345-6789",
    },
    tipoTramite: "Escritura de Compraventa",
    fecha: "2025-09-23",
    hora: "16:30",
    duracion: 90,
    sala: "Sala de Audiencias A",
    estado: "PROGRAMADA",
    notas: "Compraventa de local comercial",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-014",
    numeroSolicitud: "NT3-2025-00136",
    cliente: {
      id: "cliente-14",
      nombre: "Guillermo Torres Hernández",
      email: "guillermo.torres@email.com",
      telefono: "664-456-7890",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-24",
    hora: "12:00",
    duracion: 60,
    sala: "Sala de Audiencias B",
    estado: "PROGRAMADA",
    notas: "Testamento con cláusulas especiales",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-015",
    numeroSolicitud: "NT3-2025-00137",
    cliente: {
      id: "cliente-15",
      nombre: "Mónica Alejandra Jiménez",
      email: "monica.jimenez@email.com",
      telefono: "664-567-8901",
    },
    tipoTramite: "Escritura de Donación",
    fecha: "2025-09-24",
    hora: "14:30",
    duracion: 75,
    sala: "Sala de Audiencias C",
    estado: "PROGRAMADA",
    notas: "Donación de vehículo a organización benéfica",
    abogadoId: "notario-1",
  },
  // Citas de la semana siguiente
  {
    id: "CITA-016",
    numeroSolicitud: "NT3-2025-00138",
    cliente: {
      id: "cliente-16",
      nombre: "Eduardo Vargas Ramírez",
      email: "eduardo.vargas@email.com",
      telefono: "664-678-9012",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-09-27",
    hora: "09:30",
    duracion: 45,
    sala: "Sala de Audiencias A",
    estado: "PROGRAMADA",
    notas: "Poder notarial para gestión de inversiones",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-017",
    numeroSolicitud: "NT3-2025-00139",
    cliente: {
      id: "cliente-17",
      nombre: "Adriana Lucía Morales",
      email: "adriana.morales@email.com",
      telefono: "664-789-0123",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-27",
    hora: "11:00",
    duracion: 60,
    sala: "Sala de Audiencias B",
    estado: "PROGRAMADA",
    notas: "Testamento con fideicomiso",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-018",
    numeroSolicitud: "NT3-2025-00140",
    cliente: {
      id: "cliente-18",
      nombre: "Héctor Manuel Díaz",
      email: "hector.diaz@email.com",
      telefono: "664-890-1234",
    },
    tipoTramite: "Escritura de Compraventa",
    fecha: "2025-09-28",
    hora: "15:00",
    duracion: 90,
    sala: "Sala de Audiencias C",
    estado: "PROGRAMADA",
    notas: "Compraventa de terreno con construcción",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-019",
    numeroSolicitud: "NT3-2025-00141",
    cliente: {
      id: "cliente-19",
      nombre: "Verónica Esperanza Cruz",
      email: "veronica.cruz@email.com",
      telefono: "664-901-2345",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-09-29",
    hora: "10:00",
    duracion: 45,
    sala: "Sala de Audiencias A",
    estado: "PROGRAMADA",
    notas: "Poder notarial para gestión de seguros",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-020",
    numeroSolicitud: "NT3-2025-00142",
    cliente: {
      id: "cliente-20",
      nombre: "Oscar Daniel Peña",
      email: "oscar.pena@email.com",
      telefono: "664-012-3456",
    },
    tipoTramite: "Escritura de Donación",
    fecha: "2025-09-30",
    hora: "14:00",
    duracion: 75,
    sala: "Sala de Audiencias B",
    estado: "PROGRAMADA",
    notas: "Donación de bienes inmuebles a hijos",
    abogadoId: "notario-1",
  },
  // Algunas citas canceladas y en curso para variedad
  {
    id: "CITA-021",
    numeroSolicitud: "NT3-2025-00143",
    cliente: {
      id: "cliente-21",
      nombre: "Luis Fernando Aguilar",
      email: "luis.aguilar@email.com",
      telefono: "664-123-4567",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-13",
    hora: "10:00",
    duracion: 60,
    sala: "Sala de Audiencias A",
    estado: "CANCELADA",
    notas: "Cliente canceló por motivos personales",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-022",
    numeroSolicitud: "NT3-2025-00144",
    cliente: {
      id: "cliente-22",
      nombre: "María del Carmen Vega",
      email: "maria.vega@email.com",
      telefono: "664-234-5678",
    },
    tipoTramite: "Escritura de Compraventa",
    fecha: "2025-01-15",
    hora: "08:00",
    duracion: 90,
    sala: "Sala de Audiencias C",
    estado: "EN_CURSO",
    notas: "Firma de escritura en progreso",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-023",
    numeroSolicitud: "NT3-2025-00145",
    cliente: {
      id: "cliente-23",
      nombre: "Francisco Javier Ríos",
      email: "francisco.rios@email.com",
      telefono: "664-345-6789",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-09-12",
    hora: "16:00",
    duracion: 45,
    sala: "Sala de Audiencias B",
    estado: "COMPLETADA",
    notas: "Poder notarial para gestión de empresa",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-024",
    numeroSolicitud: "NT3-2025-00146",
    cliente: {
      id: "cliente-24",
      nombre: "Gabriela Estela Moreno",
      email: "gabriela.moreno@email.com",
      telefono: "664-456-7890",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-11",
    hora: "13:30",
    duracion: 60,
    sala: "Sala de Audiencias A",
    estado: "COMPLETADA",
    notas: "Testamento con beneficiarios múltiples",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-025",
    numeroSolicitud: "NT3-2025-00147",
    cliente: {
      id: "cliente-25",
      nombre: "Alejandro Martín Herrera",
      email: "alejandro.herrera@email.com",
      telefono: "664-567-8901",
    },
    tipoTramite: "Escritura de Donación",
    fecha: "2025-09-10",
    hora: "11:00",
    duracion: 75,
    sala: "Sala de Audiencias C",
    estado: "COMPLETADA",
    notas: "Donación de vehículo a familiar",
    abogadoId: "notario-1",
  },
  // Citas para el abogado con ID "abogado-1"
  {
    id: "CITA-026",
    numeroSolicitud: "NT3-2025-00148",
    cliente: {
      id: "cliente-26",
      nombre: "Elena Patricia Morales",
      email: "elena.morales@email.com",
      telefono: "664-111-2222",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-01-15", // Hoy
    hora: getHoraActualMasMinutos(30), // En 30 minutos (PRÓXIMA)
    duracion: 60,
    sala: "Sala de Audiencias D",
    estado: "PROGRAMADA",
    notas: "Revisión y firma de testamento con cláusulas especiales",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-027",
    numeroSolicitud: "NT3-2025-00149",
    cliente: {
      id: "cliente-27",
      nombre: "Roberto Carlos Vega",
      email: "roberto.vega@email.com",
      telefono: "664-222-3333",
    },
    tipoTramite: "Escritura de Compraventa",
    fecha: "2025-01-15", // Hoy
    hora: getHoraActualMasMinutos(120), // En 2 horas
    duracion: 90,
    sala: "Sala de Audiencias E",
    estado: "PROGRAMADA",
    notas: "Firma de escritura de compraventa de casa habitación",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-028",
    numeroSolicitud: "NT3-2025-00150",
    cliente: {
      id: "cliente-28",
      nombre: "Sandra Beatriz López",
      email: "sandra.lopez@email.com",
      telefono: "664-333-4444",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-09-17", // Mañana
    hora: "09:30",
    duracion: 45,
    sala: "Sala de Audiencias D",
    estado: "PROGRAMADA",
    notas: "Otorgamiento de poder notarial para gestión de bienes",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-029",
    numeroSolicitud: "NT3-2025-00151",
    cliente: {
      id: "cliente-29",
      nombre: "Miguel Ángel Torres",
      email: "miguel.torres@email.com",
      telefono: "664-444-5555",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-17", // Mañana
    hora: "14:30",
    duracion: 60,
    sala: "Sala de Audiencias E",
    estado: "PROGRAMADA",
    notas: "Modificación de testamento existente",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-030",
    numeroSolicitud: "NT3-2025-00152",
    cliente: {
      id: "cliente-30",
      nombre: "Carmen Rosa Delgado",
      email: "carmen.delgado@email.com",
      telefono: "664-555-6666",
    },
    tipoTramite: "Escritura de Donación",
    fecha: "2025-09-18", // Pasado mañana
    hora: "11:00",
    duracion: 75,
    sala: "Sala de Audiencias D",
    estado: "PROGRAMADA",
    notas: "Firma de escritura de donación de vehículo",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-031",
    numeroSolicitud: "NT3-2025-00153",
    cliente: {
      id: "cliente-31",
      nombre: "Francisco Javier Ruiz",
      email: "francisco.ruiz@email.com",
      telefono: "664-666-7777",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-09-15", // Ayer (completada)
    hora: "15:30",
    duracion: 45,
    sala: "Sala de Audiencias E",
    estado: "COMPLETADA",
    notas: "Poder notarial para representación legal",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-032",
    numeroSolicitud: "NT3-2025-00154",
    cliente: {
      id: "cliente-32",
      nombre: "Isabel Cristina Herrera",
      email: "isabel.herrera@email.com",
      telefono: "664-777-8888",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-20",
    hora: "10:00",
    duracion: 60,
    sala: "Sala de Audiencias D",
    estado: "PROGRAMADA",
    notas: "Revisión final y firma de testamento",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-033",
    numeroSolicitud: "NT3-2025-00155",
    cliente: {
      id: "cliente-33",
      nombre: "Fernando López García",
      email: "fernando.lopez@email.com",
      telefono: "664-888-9999",
    },
    tipoTramite: "Escritura de Compraventa",
    fecha: "2025-09-20",
    hora: "13:30",
    duracion: 90,
    sala: "Sala de Audiencias E",
    estado: "PROGRAMADA",
    notas: "Firma de escritura de compraventa de local comercial",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-034",
    numeroSolicitud: "NT3-2025-00156",
    cliente: {
      id: "cliente-34",
      nombre: "Patricia Elena Sánchez",
      email: "patricia.sanchez@email.com",
      telefono: "664-999-0000",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-09-21",
    hora: "09:00",
    duracion: 45,
    sala: "Sala de Audiencias D",
    estado: "PROGRAMADA",
    notas: "Poder notarial para administración de bienes",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-035",
    numeroSolicitud: "NT3-2025-00157",
    cliente: {
      id: "cliente-35",
      nombre: "José Antonio Mendoza",
      email: "jose.mendoza@email.com",
      telefono: "664-000-1111",
    },
    tipoTramite: "Escritura de Donación",
    fecha: "2025-09-21",
    hora: "16:00",
    duracion: 75,
    sala: "Sala de Audiencias E",
    estado: "PROGRAMADA",
    notas: "Donación de terreno a favor de hijo",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-036",
    numeroSolicitud: "NT3-2025-00158",
    cliente: {
      id: "cliente-36",
      nombre: "María del Carmen Flores",
      email: "maria.flores@email.com",
      telefono: "664-111-2222",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-22",
    hora: "08:00",
    duracion: 60,
    sala: "Sala de Audiencias D",
    estado: "PROGRAMADA",
    notas: "Testamento con fideicomiso",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-037",
    numeroSolicitud: "NT3-2025-00159",
    cliente: {
      id: "cliente-37",
      nombre: "Ricardo Silva Castro",
      email: "ricardo.silva@email.com",
      telefono: "664-222-3333",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-09-22",
    hora: "12:30",
    duracion: 45,
    sala: "Sala de Audiencias E",
    estado: "PROGRAMADA",
    notas: "Poder notarial para representación en juicio",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-038",
    numeroSolicitud: "NT3-2025-00160",
    cliente: {
      id: "cliente-38",
      nombre: "Verónica Esperanza Cruz",
      email: "veronica.cruz@email.com",
      telefono: "664-333-4444",
    },
    tipoTramite: "Escritura de Compraventa",
    fecha: "2025-09-23",
    hora: "15:00",
    duracion: 90,
    sala: "Sala de Audiencias D",
    estado: "PROGRAMADA",
    notas: "Compraventa de terreno con construcción",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-039",
    numeroSolicitud: "NT3-2025-00161",
    cliente: {
      id: "cliente-39",
      nombre: "Guillermo Torres Hernández",
      email: "guillermo.torres@email.com",
      telefono: "664-444-5555",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-24",
    hora: "11:30",
    duracion: 60,
    sala: "Sala de Audiencias E",
    estado: "PROGRAMADA",
    notas: "Testamento con cláusulas especiales",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-040",
    numeroSolicitud: "NT3-2025-00162",
    cliente: {
      id: "cliente-40",
      nombre: "Mónica Alejandra Jiménez",
      email: "monica.jimenez@email.com",
      telefono: "664-555-6666",
    },
    tipoTramite: "Escritura de Donación",
    fecha: "2025-09-24",
    hora: "14:00",
    duracion: 75,
    sala: "Sala de Audiencias D",
    estado: "PROGRAMADA",
    notas: "Donación de vehículo a organización benéfica",
    abogadoId: "abogado-1",
  },
  // Algunas citas canceladas y en curso para variedad
  {
    id: "CITA-041",
    numeroSolicitud: "NT3-2025-00163",
    cliente: {
      id: "cliente-41",
      nombre: "Luis Fernando Aguilar",
      email: "luis.aguilar@email.com",
      telefono: "664-666-7777",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-13",
    hora: "11:00",
    duracion: 60,
    sala: "Sala de Audiencias E",
    estado: "CANCELADA",
    notas: "Cliente canceló por motivos personales",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-042",
    numeroSolicitud: "NT3-2025-00164",
    cliente: {
      id: "cliente-42",
      nombre: "Adriana Lucía Morales",
      email: "adriana.morales@email.com",
      telefono: "664-777-8888",
    },
    tipoTramite: "Escritura de Compraventa",
    fecha: "2025-01-15",
    hora: "09:00",
    duracion: 90,
    sala: "Sala de Audiencias D",
    estado: "EN_CURSO",
    notas: "Firma de escritura en progreso",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-043",
    numeroSolicitud: "NT3-2025-00165",
    cliente: {
      id: "cliente-43",
      nombre: "Héctor Manuel Díaz",
      email: "hector.diaz@email.com",
      telefono: "664-888-9999",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-09-12",
    hora: "17:00",
    duracion: 45,
    sala: "Sala de Audiencias E",
    estado: "COMPLETADA",
    notas: "Poder notarial para gestión de empresa",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-044",
    numeroSolicitud: "NT3-2025-00166",
    cliente: {
      id: "cliente-44",
      nombre: "Gabriela Estela Moreno",
      email: "gabriela.moreno@email.com",
      telefono: "664-999-0000",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-11",
    hora: "14:30",
    duracion: 60,
    sala: "Sala de Audiencias D",
    estado: "COMPLETADA",
    notas: "Testamento con beneficiarios múltiples",
    abogadoId: "abogado-1",
  },
  {
    id: "CITA-045",
    numeroSolicitud: "NT3-2025-00167",
    cliente: {
      id: "cliente-45",
      nombre: "Eduardo Vargas Ramírez",
      email: "eduardo.vargas@email.com",
      telefono: "664-000-1111",
    },
    tipoTramite: "Escritura de Donación",
    fecha: "2025-09-10",
    hora: "12:00",
    duracion: 75,
    sala: "Sala de Audiencias E",
    estado: "COMPLETADA",
    notas: "Donación de vehículo a familiar",
    abogadoId: "abogado-1",
  },
  // Citas adicionales para notario-1 (Dra. María Elena Rodríguez)
  {
    id: "CITA-046",
    numeroSolicitud: "NT3-2025-00168",
    cliente: {
      id: "cliente-46",
      nombre: "Ana Patricia Herrera",
      email: "ana.herrera@email.com",
      telefono: "664-111-2222",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-01-16", // Hoy
    hora: getHoraActualMasMinutos(30), // En 30 minutos (PRÓXIMA)
    duracion: 60,
    sala: "Sala de Audiencias A",
    estado: "PROGRAMADA",
    notas: "Revisión y firma de testamento con cláusulas especiales",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-047",
    numeroSolicitud: "NT3-2025-00169",
    cliente: {
      id: "cliente-47",
      nombre: "Carlos Rodríguez Martínez",
      email: "carlos.rodriguez@email.com",
      telefono: "664-222-3333",
    },
    tipoTramite: "Escritura de Compraventa",
    fecha: "2025-01-16", // Hoy
    hora: getHoraActualMasMinutos(90), // En 1.5 horas
    duracion: 90,
    sala: "Sala de Audiencias B",
    estado: "PROGRAMADA",
    notas: "Firma de escritura de compraventa de casa habitación",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-048",
    numeroSolicitud: "NT3-2025-00170",
    cliente: {
      id: "cliente-48",
      nombre: "Roberto Silva Torres",
      email: "roberto.silva@email.com",
      telefono: "664-333-4444",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-01-17", // Mañana
    hora: "09:00",
    duracion: 45,
    sala: "Sala de Audiencias A",
    estado: "PROGRAMADA",
    notas: "Otorgamiento de poder notarial para gestión de bienes",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-049",
    numeroSolicitud: "NT3-2025-00171",
    cliente: {
      id: "cliente-49",
      nombre: "Laura Méndez García",
      email: "laura.mendez@email.com",
      telefono: "664-444-5555",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-01-17", // Mañana
    hora: "14:00",
    duracion: 60,
    sala: "Sala de Audiencias B",
    estado: "PROGRAMADA",
    notas: "Modificación de testamento existente",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-050",
    numeroSolicitud: "NT3-2025-00172",
    cliente: {
      id: "cliente-50",
      nombre: "Miguel Ángel Pérez",
      email: "miguel.perez@email.com",
      telefono: "664-555-6666",
    },
    tipoTramite: "Escritura de Donación",
    fecha: "2025-01-18", // Pasado mañana
    hora: "11:00",
    duracion: 75,
    sala: "Sala de Audiencias C",
    estado: "PROGRAMADA",
    notas: "Firma de escritura de donación de vehículo",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-051",
    numeroSolicitud: "NT3-2025-00173",
    cliente: {
      id: "cliente-51",
      nombre: "Isabel Cristina Vega",
      email: "isabel.vega@email.com",
      telefono: "664-666-7777",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-01-15", // Ayer (completada)
    hora: "15:30",
    duracion: 45,
    sala: "Sala de Audiencias A",
    estado: "COMPLETADA",
    notas: "Poder notarial para representación legal",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-052",
    numeroSolicitud: "NT3-2025-00174",
    cliente: {
      id: "cliente-52",
      nombre: "Fernando López Morales",
      email: "fernando.lopez@email.com",
      telefono: "664-777-8888",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-20",
    hora: "10:00",
    duracion: 60,
    sala: "Sala de Audiencias A",
    estado: "PROGRAMADA",
    notas: "Revisión final y firma de testamento",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-053",
    numeroSolicitud: "NT3-2025-00175",
    cliente: {
      id: "cliente-53",
      nombre: "Carmen Rosa Delgado",
      email: "carmen.delgado@email.com",
      telefono: "664-888-9999",
    },
    tipoTramite: "Escritura de Compraventa",
    fecha: "2025-09-20",
    hora: "13:30",
    duracion: 90,
    sala: "Sala de Audiencias B",
    estado: "PROGRAMADA",
    notas: "Firma de escritura de compraventa de local comercial",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-054",
    numeroSolicitud: "NT3-2025-00176",
    cliente: {
      id: "cliente-54",
      nombre: "Patricia Elena Sánchez",
      email: "patricia.sanchez@email.com",
      telefono: "664-999-0000",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-09-21",
    hora: "09:00",
    duracion: 45,
    sala: "Sala de Audiencias C",
    estado: "PROGRAMADA",
    notas: "Poder notarial para administración de bienes",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-055",
    numeroSolicitud: "NT3-2025-00177",
    cliente: {
      id: "cliente-55",
      nombre: "José Antonio Ruiz",
      email: "jose.ruiz@email.com",
      telefono: "664-000-1111",
    },
    tipoTramite: "Escritura de Donación",
    fecha: "2025-09-21",
    hora: "16:00",
    duracion: 75,
    sala: "Sala de Audiencias A",
    estado: "PROGRAMADA",
    notas: "Donación de terreno a favor de hijo",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-056",
    numeroSolicitud: "NT3-2025-00178",
    cliente: {
      id: "cliente-56",
      nombre: "María del Carmen Flores",
      email: "maria.flores@email.com",
      telefono: "664-111-2222",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-22",
    hora: "08:00",
    duracion: 60,
    sala: "Sala de Audiencias B",
    estado: "PROGRAMADA",
    notas: "Testamento con fideicomiso",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-057",
    numeroSolicitud: "NT3-2025-00179",
    cliente: {
      id: "cliente-57",
      nombre: "Ricardo Silva Castro",
      email: "ricardo.silva@email.com",
      telefono: "664-222-3333",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-09-22",
    hora: "12:30",
    duracion: 45,
    sala: "Sala de Audiencias C",
    estado: "PROGRAMADA",
    notas: "Poder notarial para representación en juicio",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-058",
    numeroSolicitud: "NT3-2025-00180",
    cliente: {
      id: "cliente-58",
      nombre: "Verónica Esperanza Cruz",
      email: "veronica.cruz@email.com",
      telefono: "664-333-4444",
    },
    tipoTramite: "Escritura de Compraventa",
    fecha: "2025-09-23",
    hora: "15:00",
    duracion: 90,
    sala: "Sala de Audiencias A",
    estado: "PROGRAMADA",
    notas: "Compraventa de terreno con construcción",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-059",
    numeroSolicitud: "NT3-2025-00181",
    cliente: {
      id: "cliente-59",
      nombre: "Guillermo Torres Hernández",
      email: "guillermo.torres@email.com",
      telefono: "664-444-5555",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-24",
    hora: "11:30",
    duracion: 60,
    sala: "Sala de Audiencias B",
    estado: "PROGRAMADA",
    notas: "Testamento con cláusulas especiales",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-060",
    numeroSolicitud: "NT3-2025-00182",
    cliente: {
      id: "cliente-60",
      nombre: "Mónica Alejandra Jiménez",
      email: "monica.jimenez@email.com",
      telefono: "664-555-6666",
    },
    tipoTramite: "Escritura de Donación",
    fecha: "2025-09-24",
    hora: "14:00",
    duracion: 75,
    sala: "Sala de Audiencias C",
    estado: "PROGRAMADA",
    notas: "Donación de vehículo a organización benéfica",
    abogadoId: "notario-1",
  },
  // Algunas citas canceladas y en curso para variedad
  {
    id: "CITA-061",
    numeroSolicitud: "NT3-2025-00183",
    cliente: {
      id: "cliente-61",
      nombre: "Luis Fernando Aguilar",
      email: "luis.aguilar@email.com",
      telefono: "664-666-7777",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-01-14",
    hora: "11:00",
    duracion: 60,
    sala: "Sala de Audiencias A",
    estado: "CANCELADA",
    notas: "Cliente canceló por motivos personales",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-062",
    numeroSolicitud: "NT3-2025-00184",
    cliente: {
      id: "cliente-62",
      nombre: "Adriana Lucía Morales",
      email: "adriana.morales@email.com",
      telefono: "664-777-8888",
    },
    tipoTramite: "Escritura de Compraventa",
    fecha: "2025-01-16",
    hora: "08:00",
    duracion: 90,
    sala: "Sala de Audiencias C",
    estado: "EN_CURSO",
    notas: "Firma de escritura en progreso",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-063",
    numeroSolicitud: "NT3-2025-00185",
    cliente: {
      id: "cliente-63",
      nombre: "Héctor Manuel Díaz",
      email: "hector.diaz@email.com",
      telefono: "664-888-9999",
    },
    tipoTramite: "Poder Notarial",
    fecha: "2025-09-13",
    hora: "17:00",
    duracion: 45,
    sala: "Sala de Audiencias B",
    estado: "COMPLETADA",
    notas: "Poder notarial para gestión de empresa",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-064",
    numeroSolicitud: "NT3-2025-00186",
    cliente: {
      id: "cliente-64",
      nombre: "Gabriela Estela Moreno",
      email: "gabriela.moreno@email.com",
      telefono: "664-999-0000",
    },
    tipoTramite: "Testamento Público Abierto",
    fecha: "2025-09-12",
    hora: "14:30",
    duracion: 60,
    sala: "Sala de Audiencias A",
    estado: "COMPLETADA",
    notas: "Testamento con beneficiarios múltiples",
    abogadoId: "notario-1",
  },
  {
    id: "CITA-065",
    numeroSolicitud: "NT3-2025-00187",
    cliente: {
      id: "cliente-65",
      nombre: "Eduardo Vargas Ramírez",
      email: "eduardo.vargas@email.com",
      telefono: "664-000-1111",
    },
    tipoTramite: "Escritura de Donación",
    fecha: "2025-09-11",
    hora: "12:00",
    duracion: 75,
    sala: "Sala de Audiencias C",
    estado: "COMPLETADA",
    notas: "Donación de vehículo a familiar",
    abogadoId: "notario-1",
  },
];

// Función para obtener citas de un abogado
export const getCitasAbogado = async (
  abogadoId: string,
  fecha?: string
): Promise<Cita[]> => {
  // Simular delay de API
  await new Promise((resolve) => setTimeout(resolve, 300));

  let citasAbogado = citas.filter((cita) => cita.abogadoId === abogadoId);

  // Si se especifica una fecha, filtrar por esa fecha
  if (fecha) {
    citasAbogado = citasAbogado.filter((cita) => cita.fecha === fecha);
  }

  // Ordenar por fecha y hora
  citasAbogado.sort((a, b) => {
    const fechaA = new Date(`${a.fecha} ${a.hora}`);
    const fechaB = new Date(`${b.fecha} ${b.hora}`);
    return fechaA.getTime() - fechaB.getTime();
  });

  return citasAbogado;
};

// Función para obtener citas del día actual
export const getCitasHoy = async (abogadoId: string): Promise<Cita[]> => {
  const hoy = new Date().toISOString().split("T")[0]; // YYYY-MM-DD
  return getCitasAbogado(abogadoId, hoy);
};

// Función para obtener próximas citas (próximas 2 horas)
export const getProximasCitas = async (abogadoId: string): Promise<Cita[]> => {
  const ahora = new Date();
  const en2Horas = new Date(ahora.getTime() + 2 * 60 * 60 * 1000);

  const citasAbogado = await getCitasAbogado(abogadoId);

  return citasAbogado.filter((cita) => {
    const fechaCita = new Date(`${cita.fecha} ${cita.hora}`);
    return (
      fechaCita >= ahora &&
      fechaCita <= en2Horas &&
      cita.estado === "PROGRAMADA"
    );
  });
};
