// Datos mock para expedientes de compraventa
import {
  ExpedienteCompraventa,
  EstadoExpediente,
  Persona,
  Inmueble,
  DocumentoCompraventa,
  DocumentoTipo,
  ESTADOS_FLUJO,
} from "./compraventa-types";

// Re-exportar tipos para uso en otros componentes
export type { ExpedienteCompraventa, EstadoExpediente };
export { ESTADOS_FLUJO };

// Generar datos mock para expedientes
export const expedientesMock: ExpedienteCompraventa[] = [
  {
    id: "exp-001",
    numeroSolicitud: "NT3-2025-001",
    fechaCreacion: "2025-01-15T10:30:00Z",
    fechaUltimaActualizacion: "2025-01-15T14:20:00Z",
    estado: "RECIBIDO",
    tipoTramite: "compraventa",
    comprador: {
      id: "comp-001",
      nombre: "Juan Carlos",
      apellidoPaterno: "Pérez",
      apellidoMaterno: "García",
      fechaNacimiento: "1986-07-02",
      lugarNacimiento: "Tijuana, B.C.",
      estadoCivil: "casado",
      nacionalidad: "Mexicana",
      curp: "HEGJ860702HMCRNN07",
      rfc: "HEGJ860702ABC",
      telefono: "+52 664 123 4567",
      email: "juan.perez@email.com",
      domicilio: {
        calle: "Av. Revolución",
        numeroExterior: "1234",
        colonia: "Centro",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22000",
        pais: "México",
      },
      ocupacion: "Ingeniero",
      tipoIdentificacion: "INE",
      numeroIdentificacion: "ABC123456789",
      esComprador: true,
      esVendedor: false,
    },
    vendedor: {
      id: "vend-001",
      nombre: "María Elena",
      apellidoPaterno: "Rodríguez",
      apellidoMaterno: "López",
      fechaNacimiento: "1975-03-15",
      lugarNacimiento: "Tijuana, B.C.",
      estadoCivil: "soltera",
      nacionalidad: "Mexicana",
      curp: "ROLM750315MBCDPR01",
      rfc: "ROLM750315XYZ",
      telefono: "+52 664 987 6543",
      email: "maria.rodriguez@email.com",
      domicilio: {
        calle: "Calle 5 de Febrero",
        numeroExterior: "567",
        colonia: "Zona Río",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22320",
        pais: "México",
      },
      ocupacion: "Comerciante",
      tipoIdentificacion: "INE",
      numeroIdentificacion: "XYZ987654321",
      esComprador: false,
      esVendedor: true,
    },
    inmueble: {
      id: "inm-001",
      tipo: "casa",
      superficie: 120,
      superficieUnidad: "m2",
      ubicacion: {
        calle: "Calle 5 de Febrero",
        numeroExterior: "567",
        colonia: "Zona Río",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22320",
        pais: "México",
      },
      descripcion:
        "Casa de 2 plantas con 3 recámaras, 2 baños, cocina integral, sala-comedor, patio trasero y cochera para 2 autos.",
      numeroEscritura: "12345",
      fechaEscritura: "2015-03-20",
      notarioEscritura: "Dr. Carlos López",
      numeroNotario: "3",
      valorAvaluo: 2500000,
      valorVenta: 2400000,
      tieneGravamen: false,
      gravamenes: [],
    },
    documentos: [
      {
        id: "doc-001",
        tipo: "identificacion_comprador",
        nombre: "INE_Juan_Perez.pdf",
        fechaSubida: "2025-01-15T10:35:00Z",
        estado: "validado",
        datosExtraidos: {
          tipoDocumento: "identificacion_comprador",
          datosPersonales: {
            nombre: "Juan Carlos",
            apellidoPaterno: "Pérez",
            apellidoMaterno: "García",
            fechaNacimiento: "1986-07-02",
            curp: "HEGJ860702HMCRNN07",
          },
          confianza: 95,
          camposExtraidos: [
            "nombre",
            "apellidoPaterno",
            "apellidoMaterno",
            "fechaNacimiento",
            "curp",
          ],
          camposFaltantes: ["rfc", "telefono", "email"],
        },
      },
      {
        id: "doc-002",
        tipo: "identificacion_vendedor",
        nombre: "INE_Maria_Rodriguez.pdf",
        fechaSubida: "2025-01-15T10:40:00Z",
        estado: "validado",
        datosExtraidos: {
          tipoDocumento: "identificacion_vendedor",
          datosPersonales: {
            nombre: "María Elena",
            apellidoPaterno: "Rodríguez",
            apellidoMaterno: "López",
            fechaNacimiento: "1975-03-15",
            curp: "ROLM750315MBCDPR01",
          },
          confianza: 92,
          camposExtraidos: [
            "nombre",
            "apellidoPaterno",
            "apellidoMaterno",
            "fechaNacimiento",
            "curp",
          ],
          camposFaltantes: ["rfc", "telefono", "email"],
        },
      },
    ],
    abogadoAsignado: "abogado-1",
    notarioAsignado: "notario-1",
    cajeroAsignado: "cajero-1",
    costos: {
      costoBase: 15000,
      aranceles: 5000,
      impuestos: 3000,
      gastos: 2000,
      total: 25000,
      saldoPendiente: 25000,
      concepto: "Compraventa de casa en Zona Río",
    },
    pagos: [],
    historial: [
      {
        id: "hist-001",
        fecha: "2025-01-15T10:30:00Z",
        accion: "Expediente creado",
        usuario: "cliente",
        detalles: "Cliente inició el proceso de compraventa",
        estadoNuevo: "RECIBIDO",
      },
    ],
    comentarios: [],
    validacionesIA: [],
  },
  {
    id: "exp-002",
    numeroSolicitud: "NT3-2025-002",
    fechaCreacion: "2025-01-14T09:15:00Z",
    fechaUltimaActualizacion: "2025-01-15T16:45:00Z",
    estado: "EN_VALIDACION",
    tipoTramite: "compraventas",
    comprador: {
      id: "comp-002",
      nombre: "Ana Patricia",
      apellidoPaterno: "González",
      apellidoMaterno: "Martínez",
      fechaNacimiento: "1990-11-22",
      lugarNacimiento: "Tijuana, B.C.",
      estadoCivil: "soltera",
      nacionalidad: "Mexicana",
      curp: "GOMA901122MBCNRN01",
      rfc: "GOMA901122DEF",
      telefono: "+52 664 555 1111",
      email: "ana.gonzalez@email.com",
      domicilio: {
        calle: "Blvd. Agua Caliente",
        numeroExterior: "890",
        colonia: "Chapultepec",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22420",
        pais: "México",
      },
      ocupacion: "Arquitecta",
      tipoIdentificacion: "INE",
      numeroIdentificacion: "DEF111222333",
      esComprador: true,
      esVendedor: false,
    },
    vendedor: {
      id: "vend-002",
      nombre: "Roberto Carlos",
      apellidoPaterno: "Hernández",
      apellidoMaterno: "Silva",
      fechaNacimiento: "1980-05-10",
      lugarNacimiento: "Tijuana, B.C.",
      estadoCivil: "casado",
      nacionalidad: "Mexicana",
      curp: "HESR800510HBCRLB01",
      rfc: "HESR800510GHI",
      telefono: "+52 664 777 8888",
      email: "roberto.hernandez@email.com",
      domicilio: {
        calle: "Av. Universidad",
        numeroExterior: "123",
        colonia: "Centro",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22000",
        pais: "México",
      },
      ocupacion: "Empresario",
      tipoIdentificacion: "INE",
      numeroIdentificacion: "GHI444555666",
      esComprador: false,
      esVendedor: true,
    },
    inmueble: {
      id: "inm-002",
      tipo: "departamento",
      superficie: 85,
      superficieUnidad: "m2",
      ubicacion: {
        calle: "Av. Universidad",
        numeroExterior: "123",
        colonia: "Centro",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22000",
        pais: "México",
      },
      descripcion:
        "Departamento de 2 recámaras, 1 baño, cocina, sala-comedor y balcón.",
      numeroEscritura: "67890",
      fechaEscritura: "2018-07-15",
      notarioEscritura: "Dra. María Elena Rodríguez",
      numeroNotario: "3",
      valorAvaluo: 1800000,
      valorVenta: 1750000,
      tieneGravamen: false,
      gravamenes: [],
    },
    documentos: [
      {
        id: "doc-003",
        tipo: "identificacion_comprador",
        nombre: "INE_Ana_Gonzalez.pdf",
        fechaSubida: "2025-01-14T09:20:00Z",
        estado: "validado",
      },
      {
        id: "doc-004",
        tipo: "identificacion_vendedor",
        nombre: "INE_Roberto_Hernandez.pdf",
        fechaSubida: "2025-01-14T09:25:00Z",
        estado: "validado",
      },
      {
        id: "doc-005",
        tipo: "avaluo_inmueble",
        nombre: "Avaluo_Departamento_Universidad.pdf",
        fechaSubida: "2025-01-14T09:30:00Z",
        estado: "validado",
      },
    ],
    abogadoAsignado: "abogado-2",
    notarioAsignado: "notario-1",
    cajeroAsignado: "cajero-1",
    costos: {
      costoBase: 12000,
      aranceles: 4000,
      impuestos: 2500,
      gastos: 1500,
      total: 20000,
      saldoPendiente: 20000,
      concepto: "Compraventa de departamento en Centro",
    },
    pagos: [],
    historial: [
      {
        id: "hist-002",
        fecha: "2025-01-14T09:15:00Z",
        accion: "Expediente creado",
        usuario: "cliente",
        detalles: "Cliente inició el proceso de compraventa",
        estadoNuevo: "RECIBIDO",
      },
      {
        id: "hist-003",
        fecha: "2025-01-15T16:45:00Z",
        accion: "Enviado a validación",
        usuario: "abogado-1",
        detalles: "Abogado asignado para revisión de documentos",
        estadoAnterior: "RECIBIDO",
        estadoNuevo: "EN_VALIDACION",
      },
    ],
    comentarios: [
      {
        id: "com-001",
        fecha: "2025-01-15T16:45:00Z",
        usuario: "abogado-1",
        comentario: "Documentos recibidos correctamente. Iniciando validación.",
        tipo: "general",
      },
    ],
    validacionesIA: [],
  },
  {
    id: "exp-003",
    numeroSolicitud: "NT3-2025-003",
    fechaCreacion: "2025-01-13T14:20:00Z",
    fechaUltimaActualizacion: "2025-01-15T11:30:00Z",
    estado: "EN_PREPARACION",
    tipoTramite: "compraventas",
    comprador: {
      id: "comp-003",
      nombre: "Luis Fernando",
      apellidoPaterno: "Morales",
      apellidoMaterno: "Castro",
      fechaNacimiento: "1985-09-08",
      lugarNacimiento: "Tijuana, B.C.",
      estadoCivil: "casado",
      nacionalidad: "Mexicana",
      curp: "MOCL850908HBCRSR01",
      rfc: "MOCL850908JKL",
      telefono: "+52 664 333 4444",
      email: "luis.morales@email.com",
      domicilio: {
        calle: "Calle 2da",
        numeroExterior: "456",
        colonia: "Centro",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22000",
        pais: "México",
      },
      ocupacion: "Abogado",
      tipoIdentificacion: "INE",
      numeroIdentificacion: "JKL777888999",
      esComprador: true,
      esVendedor: false,
    },
    vendedor: {
      id: "vend-003",
      nombre: "Carmen Rosa",
      apellidoPaterno: "Vega",
      apellidoMaterno: "Ruiz",
      fechaNacimiento: "1970-12-03",
      lugarNacimiento: "Tijuana, B.C.",
      estadoCivil: "viuda",
      nacionalidad: "Mexicana",
      curp: "VERC701203MBCGZR01",
      rfc: "VERC701203MNO",
      telefono: "+52 664 999 0000",
      email: "carmen.vega@email.com",
      domicilio: {
        calle: "Av. Revolución",
        numeroExterior: "789",
        colonia: "Centro",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22000",
        pais: "México",
      },
      ocupacion: "Pensionada",
      tipoIdentificacion: "INE",
      numeroIdentificacion: "MNO000111222",
      esComprador: false,
      esVendedor: true,
    },
    inmueble: {
      id: "inm-003",
      tipo: "terreno",
      superficie: 500,
      superficieUnidad: "m2",
      ubicacion: {
        calle: "Av. Revolución",
        numeroExterior: "789",
        colonia: "Centro",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22000",
        pais: "México",
      },
      descripcion:
        "Terreno comercial de 500 m² en zona céntrica, ideal para construcción de local comercial.",
      numeroEscritura: "11111",
      fechaEscritura: "2010-01-20",
      notarioEscritura: "Dr. Carlos López",
      numeroNotario: "3",
      valorAvaluo: 3200000,
      valorVenta: 3000000,
      tieneGravamen: false,
      gravamenes: [],
    },
    documentos: [
      {
        id: "doc-006",
        tipo: "identificacion_comprador",
        nombre: "INE_Luis_Morales.pdf",
        fechaSubida: "2025-01-13T14:25:00Z",
        estado: "validado",
      },
      {
        id: "doc-007",
        tipo: "identificacion_vendedor",
        nombre: "INE_Carmen_Vega.pdf",
        fechaSubida: "2025-01-13T14:30:00Z",
        estado: "validado",
      },
      {
        id: "doc-008",
        tipo: "avaluo_inmueble",
        nombre: "Avaluo_Terreno_Revolucion.pdf",
        fechaSubida: "2025-01-13T14:35:00Z",
        estado: "validado",
      },
      {
        id: "doc-009",
        tipo: "escritura_propiedad",
        nombre: "Escritura_Terreno_11111.pdf",
        fechaSubida: "2025-01-13T14:40:00Z",
        estado: "validado",
      },
      {
        id: "doc-010",
        tipo: "certificado_libertad_gravamen",
        nombre: "CLG_Terreno_Revolucion.pdf",
        fechaSubida: "2025-01-13T14:45:00Z",
        estado: "validado",
      },
    ],
    abogadoAsignado: "abogado-2",
    notarioAsignado: "notario-1",
    cajeroAsignado: "cajero-1",
    costos: {
      costoBase: 20000,
      aranceles: 8000,
      impuestos: 5000,
      gastos: 3000,
      total: 36000,
      saldoPendiente: 18000,
      concepto: "Compraventa de terreno comercial en Centro",
    },
    pagos: [
      {
        id: "pago-001",
        monto: 18000,
        fecha: "2025-01-14T10:00:00Z",
        metodo: "transferencia",
        referencia: "TXN123456789",
        estado: "confirmado",
        confirmadoPor: "cajero-1",
        observaciones: "Pago parcial confirmado",
      },
    ],
    historial: [
      {
        id: "hist-004",
        fecha: "2025-01-13T14:20:00Z",
        accion: "Expediente creado",
        usuario: "cliente",
        detalles: "Cliente inició el proceso de compraventa",
        estadoNuevo: "RECIBIDO",
      },
      {
        id: "hist-005",
        fecha: "2025-01-14T09:00:00Z",
        accion: "Enviado a validación",
        usuario: "abogado-1",
        detalles: "Abogado asignado para revisión de documentos",
        estadoAnterior: "RECIBIDO",
        estadoNuevo: "EN_VALIDACION",
      },
      {
        id: "hist-006",
        fecha: "2025-01-14T15:30:00Z",
        accion: "Validación completada",
        usuario: "abogado-1",
        detalles: "Todos los documentos validados correctamente",
        estadoAnterior: "EN_VALIDACION",
        estadoNuevo: "EN_PREPARACION",
      },
      {
        id: "hist-007",
        fecha: "2025-01-15T11:30:00Z",
        accion: "Pago parcial recibido",
        usuario: "cajero-1",
        detalles: "Pago parcial de $18,000 confirmado",
        estadoAnterior: "EN_PREPARACION",
        estadoNuevo: "EN_PREPARACION",
      },
    ],
    comentarios: [
      {
        id: "com-002",
        fecha: "2025-01-14T15:30:00Z",
        usuario: "abogado-1",
        comentario: "Documentos validados. Iniciando preparación de escritura.",
        tipo: "general",
      },
      {
        id: "com-003",
        fecha: "2025-01-15T11:30:00Z",
        usuario: "cajero-1",
        comentario: "Pago parcial confirmado. Saldo pendiente: $18,000",
        tipo: "observacion",
      },
    ],
    validacionesIA: [
      {
        id: "val-001",
        tipo: "validacion_avaluo",
        fecha: "2025-01-14T15:00:00Z",
        resultado: "aprobado",
        confianza: 95,
        detalles:
          "Valor de venta ($3,000,000) está dentro del rango permitido vs avalúo ($3,200,000)",
        documentoRelacionado: "doc-008",
      },
      {
        id: "val-002",
        tipo: "validacion_propiedad",
        fecha: "2025-01-14T15:05:00Z",
        resultado: "aprobado",
        confianza: 98,
        detalles: "Propietario verificado correctamente en escritura y CLG",
        documentoRelacionado: "doc-009",
      },
    ],
  },
  {
    id: "exp-004",
    numeroSolicitud: "NT3-2025-004",
    fechaCreacion: "2025-01-12T08:30:00Z",
    fechaUltimaActualizacion: "2025-01-15T17:00:00Z",
    estado: "LISTO_PARA_FIRMA",
    tipoTramite: "compraventas",
    comprador: {
      id: "comp-004",
      nombre: "Sofia Alejandra",
      apellidoPaterno: "Mendoza",
      apellidoMaterno: "Torres",
      fechaNacimiento: "1988-04-18",
      lugarNacimiento: "Tijuana, B.C.",
      estadoCivil: "casada",
      nacionalidad: "Mexicana",
      curp: "METO880418MBCNRF01",
      rfc: "METO880418PQR",
      telefono: "+52 664 222 3333",
      email: "sofia.mendoza@email.com",
      domicilio: {
        calle: "Av. Insurgentes",
        numeroExterior: "321",
        colonia: "Centro",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22000",
        pais: "México",
      },
      ocupacion: "Doctora",
      tipoIdentificacion: "INE",
      numeroIdentificacion: "PQR111222333",
      esComprador: true,
      esVendedor: false,
    },
    vendedor: {
      id: "vend-004",
      nombre: "Miguel Angel",
      apellidoPaterno: "Delgado",
      apellidoMaterno: "Ramirez",
      fechaNacimiento: "1978-08-25",
      lugarNacimiento: "Tijuana, B.C.",
      estadoCivil: "casado",
      nacionalidad: "Mexicana",
      curp: "DERM780825HBCLGL01",
      rfc: "DERM780825STU",
      telefono: "+52 664 444 5555",
      email: "miguel.delgado@email.com",
      domicilio: {
        calle: "Calle 3ra",
        numeroExterior: "789",
        colonia: "Centro",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22000",
        pais: "México",
      },
      ocupacion: "Ingeniero",
      tipoIdentificacion: "INE",
      numeroIdentificacion: "STU444555666",
      esComprador: false,
      esVendedor: true,
    },
    inmueble: {
      id: "inm-004",
      tipo: "casa",
      superficie: 150,
      superficieUnidad: "m2",
      ubicacion: {
        calle: "Calle 3ra",
        numeroExterior: "789",
        colonia: "Centro",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22000",
        pais: "México",
      },
      descripcion:
        "Casa de 2 plantas con 4 recámaras, 3 baños, cocina integral, sala-comedor, patio trasero y cochera para 3 autos.",
      numeroEscritura: "22222",
      fechaEscritura: "2012-06-10",
      notarioEscritura: "Dra. María Elena Rodríguez",
      numeroNotario: "3",
      valorAvaluo: 2800000,
      valorVenta: 2700000,
      tieneGravamen: false,
      gravamenes: [],
    },
    documentos: [
      {
        id: "doc-011",
        tipo: "identificacion_comprador",
        nombre: "INE_Sofia_Mendoza.pdf",
        fechaSubida: "2025-01-12T08:35:00Z",
        estado: "validado",
      },
      {
        id: "doc-012",
        tipo: "identificacion_vendedor",
        nombre: "INE_Miguel_Delgado.pdf",
        fechaSubida: "2025-01-12T08:40:00Z",
        estado: "validado",
      },
      {
        id: "doc-013",
        tipo: "avaluo_inmueble",
        nombre: "Avaluo_Casa_Insurgentes.pdf",
        fechaSubida: "2025-01-12T08:45:00Z",
        estado: "validado",
      },
      {
        id: "doc-014",
        tipo: "escritura_propiedad",
        nombre: "Escritura_Casa_22222.pdf",
        fechaSubida: "2025-01-12T08:50:00Z",
        estado: "validado",
      },
      {
        id: "doc-015",
        tipo: "certificado_libertad_gravamen",
        nombre: "CLG_Casa_Insurgentes.pdf",
        fechaSubida: "2025-01-12T08:55:00Z",
        estado: "validado",
      },
    ],
    abogadoAsignado: "abogado-2",
    notarioAsignado: "notario-1",
    cajeroAsignado: "cajero-1",
    costos: {
      costoBase: 18000,
      aranceles: 7000,
      impuestos: 4500,
      gastos: 2500,
      total: 32000,
      saldoPendiente: 0, // ¡PAGO COMPLETO!
      concepto: "Compraventa de casa en Centro",
    },
    pagos: [
      {
        id: "pago-002",
        monto: 32000,
        fecha: "2025-01-14T14:00:00Z",
        metodo: "transferencia",
        referencia: "TXN987654321",
        estado: "confirmado",
        confirmadoPor: "cajero-1",
        observaciones: "Pago completo confirmado",
      },
    ],
    historial: [
      {
        id: "hist-008",
        fecha: "2025-01-12T08:30:00Z",
        accion: "Expediente creado",
        usuario: "cliente",
        detalles: "Cliente inició el proceso de compraventa",
        estadoNuevo: "RECIBIDO",
      },
      {
        id: "hist-009",
        fecha: "2025-01-13T09:00:00Z",
        accion: "Enviado a validación",
        usuario: "abogado-1",
        detalles: "Abogado asignado para revisión de documentos",
        estadoAnterior: "RECIBIDO",
        estadoNuevo: "EN_VALIDACION",
      },
      {
        id: "hist-010",
        fecha: "2025-01-13T16:30:00Z",
        accion: "Validación completada",
        usuario: "abogado-1",
        detalles: "Todos los documentos validados correctamente",
        estadoAnterior: "EN_VALIDACION",
        estadoNuevo: "EN_PREPARACION",
      },
      {
        id: "hist-011",
        fecha: "2025-01-14T14:00:00Z",
        accion: "Pago completo recibido",
        usuario: "cajero-1",
        detalles: "Pago completo de $32,000 confirmado",
        estadoAnterior: "EN_PREPARACION",
        estadoNuevo: "LISTO_PARA_FIRMA",
      },
    ],
    comentarios: [
      {
        id: "com-004",
        fecha: "2025-01-13T16:30:00Z",
        usuario: "abogado-1",
        comentario: "Documentos validados. Preparando escritura.",
        tipo: "general",
      },
      {
        id: "com-005",
        fecha: "2025-01-14T14:00:00Z",
        usuario: "cajero-1",
        comentario: "Pago completo confirmado. Listo para firma.",
        tipo: "observacion",
      },
    ],
    validacionesIA: [
      {
        id: "val-003",
        tipo: "validacion_avaluo",
        fecha: "2025-01-13T16:00:00Z",
        resultado: "aprobado",
        confianza: 96,
        detalles:
          "Valor de venta ($2,700,000) está dentro del rango permitido vs avalúo ($2,800,000)",
        documentoRelacionado: "doc-013",
      },
      {
        id: "val-004",
        tipo: "validacion_propiedad",
        fecha: "2025-01-13T16:05:00Z",
        resultado: "aprobado",
        confianza: 99,
        detalles: "Propietario verificado correctamente en escritura y CLG",
        documentoRelacionado: "doc-014",
      },
    ],
  },
  {
    id: "exp-005",
    numeroSolicitud: "NT3-2025-005",
    fechaCreacion: "2025-01-10T09:15:00Z",
    fechaUltimaActualizacion: "2025-01-15T11:30:00Z",
    estado: "RECIBIDO",
    tipoTramite: "testamento",
    comprador: {
      id: "comp-005",
      nombre: "Roberto Carlos",
      apellidoPaterno: "Hernández",
      apellidoMaterno: "García",
      fechaNacimiento: "1955-03-22",
      lugarNacimiento: "Tijuana, B.C.",
      estadoCivil: "viudo",
      nacionalidad: "Mexicana",
      curp: "HERG550322HBCRRB01",
      rfc: "HERG550322ABC",
      telefono: "+52 664 777 8888",
      email: "roberto.hernandez@email.com",
      domicilio: {
        calle: "Av. Universidad",
        numeroExterior: "456",
        colonia: "Zona Río",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22320",
        pais: "México",
      },
      ocupacion: "Retirado",
      tipoIdentificacion: "INE",
      numeroIdentificacion: "ABC777888999",
      esComprador: true,
      esVendedor: false,
    },
    vendedor: {
      id: "vend-005",
      nombre: "Roberto Carlos",
      apellidoPaterno: "Hernández",
      apellidoMaterno: "García",
      fechaNacimiento: "1955-03-22",
      lugarNacimiento: "Tijuana, B.C.",
      estadoCivil: "viudo",
      nacionalidad: "Mexicana",
      curp: "HERG550322HBCRRB01",
      rfc: "HERG550322ABC",
      telefono: "+52 664 777 8888",
      email: "roberto.hernandez@email.com",
      domicilio: {
        calle: "Av. Universidad",
        numeroExterior: "456",
        colonia: "Zona Río",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22320",
        pais: "México",
      },
      ocupacion: "Retirado",
      tipoIdentificacion: "INE",
      numeroIdentificacion: "ABC777888999",
      esComprador: false,
      esVendedor: true,
    },
    inmueble: {
      id: "inm-005",
      tipo: "casa",
      superficie: 200,
      superficieUnidad: "m2",
      ubicacion: {
        calle: "Av. Universidad",
        numeroExterior: "456",
        colonia: "Zona Río",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22320",
        pais: "México",
      },
      descripcion:
        "Casa de 3 plantas con 5 recámaras, 4 baños, cocina integral, sala-comedor, terraza y cochera para 4 autos.",
      numeroEscritura: "33333",
      fechaEscritura: "1998-12-15",
      notarioEscritura: "Dr. Carlos Mendoza",
      numeroNotario: "2",
      valorAvaluo: 4500000,
      valorVenta: 4500000,
      tieneGravamen: false,
      gravamenes: [],
    },
    documentos: [
      {
        id: "doc-016",
        tipo: "identificacion_comprador",
        nombre: "INE_Roberto_Hernandez.pdf",
        fechaSubida: "2025-01-10T09:20:00Z",
        estado: "validado",
      },
      {
        id: "doc-017",
        tipo: "avaluo_inmueble",
        nombre: "Avaluo_Casa_Universidad.pdf",
        fechaSubida: "2025-01-10T09:25:00Z",
        estado: "validado",
      },
      {
        id: "doc-018",
        tipo: "escritura_propiedad",
        nombre: "Escritura_Casa_33333.pdf",
        fechaSubida: "2025-01-10T09:30:00Z",
        estado: "subido",
      },
    ],
    abogadoAsignado: "abogado-1",
    notarioAsignado: "notario-1",
    cajeroAsignado: "cajero-1",
    costos: {
      costoBase: 25000,
      aranceles: 10000,
      impuestos: 6000,
      gastos: 3000,
      total: 44000,
      saldoPendiente: 44000,
      concepto: "Testamento de casa en Zona Río",
    },
    pagos: [],
    historial: [
      {
        id: "hist-012",
        fecha: "2025-01-10T09:15:00Z",
        accion: "Testamento creado",
        usuario: "cliente",
        detalles: "Cliente inició el proceso de testamento",
        estadoNuevo: "RECIBIDO",
      },
      {
        id: "hist-013",
        fecha: "2025-01-12T10:00:00Z",
        accion: "Enviado a validación",
        usuario: "abogado-1",
        detalles: "Abogado asignado para revisión de documentos",
        estadoAnterior: "RECIBIDO",
        estadoNuevo: "EN_VALIDACION",
      },
    ],
    comentarios: [
      {
        id: "com-006",
        fecha: "2025-01-12T10:00:00Z",
        usuario: "abogado-1",
        comentario: "Revisando documentos del testamento.",
        tipo: "general",
      },
    ],
    validacionesIA: [
      {
        id: "val-005",
        tipo: "validacion_propiedad",
        fecha: "2025-01-12T10:05:00Z",
        resultado: "aprobado",
        confianza: 97,
        detalles: "Propietario verificado correctamente en escritura",
        documentoRelacionado: "doc-018",
      },
    ],
  },
  {
    id: "exp-006",
    numeroSolicitud: "NT3-2025-006",
    fechaCreacion: "2025-01-08T14:20:00Z",
    fechaUltimaActualizacion: "2025-01-14T16:45:00Z",
    estado: "RECIBIDO",
    tipoTramite: "donacion",
    comprador: {
      id: "comp-006",
      nombre: "Patricia Elena",
      apellidoPaterno: "Morales",
      apellidoMaterno: "Vega",
      fechaNacimiento: "1982-07-18",
      lugarNacimiento: "Tijuana, B.C.",
      estadoCivil: "casada",
      nacionalidad: "Mexicana",
      curp: "MOVP820718MBCRGT01",
      rfc: "MOVP820718XYZ",
      telefono: "+52 664 999 0000",
      email: "patricia.morales@email.com",
      domicilio: {
        calle: "Calle 5ta",
        numeroExterior: "123",
        colonia: "Centro",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22000",
        pais: "México",
      },
      ocupacion: "Contadora",
      tipoIdentificacion: "INE",
      numeroIdentificacion: "XYZ999000111",
      esComprador: true,
      esVendedor: false,
    },
    vendedor: {
      id: "vend-006",
      nombre: "Carlos Alberto",
      apellidoPaterno: "Rodríguez",
      apellidoMaterno: "López",
      fechaNacimiento: "1975-11-30",
      lugarNacimiento: "Tijuana, B.C.",
      estadoCivil: "casado",
      nacionalidad: "Mexicana",
      curp: "ROLC751130HBCDPR01",
      rfc: "ROLC751130DEF",
      telefono: "+52 664 111 2222",
      email: "carlos.rodriguez@email.com",
      domicilio: {
        calle: "Calle 5ta",
        numeroExterior: "123",
        colonia: "Centro",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22000",
        pais: "México",
      },
      ocupacion: "Ingeniero",
      tipoIdentificacion: "INE",
      numeroIdentificacion: "DEF111222333",
      esComprador: false,
      esVendedor: true,
    },
    inmueble: {
      id: "inm-006",
      tipo: "departamento",
      superficie: 85,
      superficieUnidad: "m2",
      ubicacion: {
        calle: "Calle 5ta",
        numeroExterior: "123",
        colonio: "Centro",
        municipio: "Tijuana",
        estado: "Baja California",
        codigoPostal: "22000",
        pais: "México",
      },
      descripcion:
        "Departamento de 2 recámaras, 2 baños, cocina integral, sala-comedor y balcón.",
      numeroEscritura: "44444",
      fechaEscritura: "2015-08-20",
      notarioEscritura: "Dra. María Elena Rodríguez",
      numeroNotario: "3",
      valorAvaluo: 1800000,
      valorVenta: 1750000,
      tieneGravamen: false,
      gravamenes: [],
    },
    documentos: [
      {
        id: "doc-019",
        tipo: "identificacion_comprador",
        nombre: "INE_Patricia_Morales.pdf",
        fechaSubida: "2025-01-08T14:25:00Z",
        estado: "validado",
      },
      {
        id: "doc-020",
        tipo: "identificacion_vendedor",
        nombre: "INE_Carlos_Rodriguez.pdf",
        fechaSubida: "2025-01-08T14:30:00Z",
        estado: "validado",
      },
      {
        id: "doc-021",
        tipo: "avaluo_inmueble",
        nombre: "Avaluo_Departamento_Centro.pdf",
        fechaSubida: "2025-01-08T14:35:00Z",
        estado: "validado",
      },
      {
        id: "doc-022",
        tipo: "escritura_propiedad",
        nombre: "Escritura_Departamento_44444.pdf",
        fechaSubida: "2025-01-08T14:40:00Z",
        estado: "validado",
      },
      {
        id: "doc-023",
        tipo: "certificado_libertad_gravamen",
        nombre: "CLG_Departamento_Centro.pdf",
        fechaSubida: "2025-01-08T14:45:00Z",
        estado: "validado",
      },
    ],
    abogadoAsignado: "abogado-1",
    notarioAsignado: "notario-1",
    cajeroAsignado: "cajero-1",
    costos: {
      costoBase: 12000,
      aranceles: 5000,
      impuestos: 3000,
      gastos: 1500,
      total: 21500,
      saldoPendiente: 10000,
      concepto: "Donación de departamento en Centro",
    },
    pagos: [
      {
        id: "pago-003",
        monto: 11500,
        fecha: "2025-01-12T15:00:00Z",
        metodo: "transferencia",
        referencia: "TXN555666777",
        estado: "confirmado",
        confirmadoPor: "cajero-1",
        observaciones: "Pago parcial confirmado",
      },
    ],
    historial: [
      {
        id: "hist-014",
        fecha: "2025-01-08T14:20:00Z",
        accion: "Donación creada",
        usuario: "cliente",
        detalles: "Cliente inició el proceso de donación",
        estadoNuevo: "RECIBIDO",
      },
      {
        id: "hist-015",
        fecha: "2025-01-10T11:00:00Z",
        accion: "Enviado a validación",
        usuario: "abogado-1",
        detalles: "Abogado asignado para revisión de documentos",
        estadoAnterior: "RECIBIDO",
        estadoNuevo: "EN_VALIDACION",
      },
      {
        id: "hist-016",
        fecha: "2025-01-12T15:00:00Z",
        accion: "Pago parcial recibido",
        usuario: "cajero-1",
        detalles: "Pago parcial de $11,500 confirmado",
        estadoAnterior: "EN_VALIDACION",
        estadoNuevo: "EN_PREPARACION",
      },
    ],
    comentarios: [
      {
        id: "com-007",
        fecha: "2025-01-10T11:00:00Z",
        usuario: "abogado-1",
        comentario: "Documentos validados. Preparando escritura de donación.",
        tipo: "general",
      },
      {
        id: "com-008",
        fecha: "2025-01-12T15:00:00Z",
        usuario: "cajero-1",
        comentario: "Pago parcial confirmado. Pendiente $10,000.",
        tipo: "observacion",
      },
    ],
    validacionesIA: [
      {
        id: "val-006",
        tipo: "validacion_avaluo",
        fecha: "2025-01-10T11:05:00Z",
        resultado: "aprobado",
        confianza: 94,
        detalles:
          "Valor de donación ($1,750,000) está dentro del rango permitido vs avalúo ($1,800,000)",
        documentoRelacionado: "doc-021",
      },
      {
        id: "val-007",
        tipo: "validacion_propiedad",
        fecha: "2025-01-10T11:10:00Z",
        resultado: "aprobado",
        confianza: 98,
        detalles: "Propietario verificado correctamente en escritura y CLG",
        documentoRelacionado: "doc-022",
      },
    ],
  },
];

// Función para obtener expedientes por estado
export const getExpedientesByEstado = (
  estado: EstadoExpediente
): ExpedienteCompraventa[] => {
  return expedientesMock.filter((exp) => exp.estado === estado);
};

// Función para obtener expedientes por abogado asignado
export const getExpedientesByAbogado = (
  abogadoId: string
): ExpedienteCompraventa[] => {
  return expedientesMock.filter((exp) => exp.abogadoAsignado === abogadoId);
};

// Función para obtener expediente por ID
export const getExpedienteById = (
  id: string
): ExpedienteCompraventa | undefined => {
  return expedientesMock.find((exp) => exp.id === id);
};

// Función para actualizar estado de expediente
export const updateExpedienteEstado = (
  id: string,
  nuevoEstado: EstadoExpediente,
  usuario: string
): boolean => {
  const expediente = expedientesMock.find((exp) => exp.id === id);
  if (!expediente) return false;

  const estadoAnterior = expediente.estado;
  expediente.estado = nuevoEstado;
  expediente.fechaUltimaActualizacion = new Date().toISOString();

  // Agregar al historial
  expediente.historial.push({
    id: `hist-${Date.now()}`,
    fecha: new Date().toISOString(),
    accion: `Estado cambiado a ${nuevoEstado}`,
    usuario,
    detalles: `Expediente movido de ${estadoAnterior} a ${nuevoEstado}`,
    estadoAnterior,
    estadoNuevo: nuevoEstado,
  });

  return true;
};

// Función para agregar comentario a expediente
export const addComentarioExpediente = (
  id: string,
  comentario: string,
  usuario: string,
  tipo: "general" | "observacion" | "requerimiento"
): boolean => {
  const expediente = expedientesMock.find((exp) => exp.id === id);
  if (!expediente) return false;

  expediente.comentarios.push({
    id: `com-${Date.now()}`,
    fecha: new Date().toISOString(),
    usuario,
    comentario,
    tipo,
  });

  expediente.fechaUltimaActualizacion = new Date().toISOString();
  return true;
};
